//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademik_Ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Akademik_Ders()
        {
            this.Akademik_Ders_Öğrenci = new HashSet<Akademik_Ders_Öğrenci>();
            this.Ders_Ekleme_Çıkarma = new HashSet<Ders_Ekleme_Çıkarma>();
        }
    
        public int Akademik_Ders_Id { get; set; }
        public Nullable<int> Danışman_Id { get; set; }
        public Nullable<int> Uzmanlık_Id { get; set; }
        public string Ders_Tanımı { get; set; }
        public string Ders_Kod { get; set; }
        public Nullable<int> AKTS { get; set; }
        public Nullable<int> KREDI { get; set; }
        public string DIL_ID { get; set; }
        public string TUR_ID { get; set; }
        public Nullable<int> Psf_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akademik_Ders_Öğrenci> Akademik_Ders_Öğrenci { get; set; }
        public virtual Danışman Danışman { get; set; }
        public virtual Uzmanlık_Alanı Uzmanlık_Alanı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ders_Ekleme_Çıkarma> Ders_Ekleme_Çıkarma { get; set; }
    }
}
