//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademik_Ders_Öğrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Akademik_Ders_Öğrenci()
        {
            this.Not_Tablosu = new HashSet<Not_Tablosu>();
        }
    
        public int Akademik_Ders_Öğrenci_Id { get; set; }
        public Nullable<int> Öğrenci_Id { get; set; }
        public Nullable<int> Akademik_Ders_Id { get; set; }
    
        public virtual Akademik_Ders Akademik_Ders { get; set; }
        public virtual Öğrenci Öğrenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Not_Tablosu> Not_Tablosu { get; set; }
    }
}
