//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademik_Dönem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Akademik_Dönem()
        {
            this.Ders_Ekleme_Çıkarma = new HashSet<Ders_Ekleme_Çıkarma>();
        }
    
        public int Akademik_Dönem_Id { get; set; }
        public string Akademik_Dönem1 { get; set; }
        public string Yarıyıl { get; set; }
        public Nullable<int> Toplam_Hafta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ders_Ekleme_Çıkarma> Ders_Ekleme_Çıkarma { get; set; }
    }
}
