//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danışman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danışman()
        {
            this.Akademik_Ders = new HashSet<Akademik_Ders>();
            this.Öğrenci = new HashSet<Öğrenci>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int Danışman_Id { get; set; }
        public Nullable<int> Kullanıcı_Id { get; set; }
        public string Unvan { get; set; }
        public string Danışman_Ad { get; set; }
        public string Danışman_Soyad { get; set; }
        public Nullable<System.DateTime> Danışman_Doğum_Tarihi { get; set; }
        public string Danışman_Doğum_Yeri { get; set; }
        public string Danışman_Uyruğu { get; set; }
        public Nullable<System.DateTime> Uzmanlık_Başlama_Tarihi { get; set; }
        public Nullable<int> Psf_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akademik_Ders> Akademik_Ders { get; set; }
        public virtual Kullanıcı Kullanıcı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Öğrenci> Öğrenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
