//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders_Ekleme_Çıkarma
    {
        public int Ders_Ekleme_Cikarma_Id { get; set; }
        public Nullable<int> Akademik_Dönem_Id { get; set; }
        public Nullable<int> Akademik_Ders_Id { get; set; }
    
        public virtual Akademik_Ders Akademik_Ders { get; set; }
        public virtual Akademik_Dönem Akademik_Dönem { get; set; }
    }
}
