//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kanaat_Formu
    {
        public int Kanaat_Form_Id { get; set; }
        public Nullable<int> Mesleki_Ahlak_Id { get; set; }
        public Nullable<int> Yönetme_Yeteneği_Id { get; set; }
        public Nullable<int> Araştırma_Yeteneği_Id { get; set; }
        public Nullable<int> Çalişma_Yeteneği_Id { get; set; }
        public Nullable<int> Göreve_Bağlılık_Id { get; set; }
        public Nullable<int> Öğrenci_Id { get; set; }
        public Nullable<double> Deg_Not { get; set; }
        public string Açıklama { get; set; }
        public string Formu_Dolduran { get; set; }
        public Nullable<int> Düşük_Tekrar { get; set; }
    
        public virtual Araştırma_Yeteneği Araştırma_Yeteneği { get; set; }
        public virtual Çalışma_Yeteneği Çalışma_Yeteneği { get; set; }
        public virtual Göreve_Bağlılık Göreve_Bağlılık { get; set; }
        public virtual Mesleki_Ahlak Mesleki_Ahlak { get; set; }
        public virtual Öğrenci Öğrenci { get; set; }
        public virtual Yönetme_Yeteneği Yönetme_Yeteneği { get; set; }
    }
}
