//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanıcı()
        {
            this.Danışman = new HashSet<Danışman>();
            this.Öğrenci = new HashSet<Öğrenci>();
        }
    
        public int Kullanıcı_Id { get; set; }
        public string Kullanıcı_Adı { get; set; }
        public string Parola { get; set; }
        public int Rol { get; set; }
        public string Mail { get; set; }
        public string Tel { get; set; }
        public string TC_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danışman> Danışman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Öğrenci> Öğrenci { get; set; }
    }
}
