//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not_Tablosu
    {
        public int Not_Id { get; set; }
        public Nullable<int> Akademik_Ders_Öğrenci_Id { get; set; }
        public Nullable<double> Sınav_Not { get; set; }
    
        public virtual Akademik_Ders_Öğrenci Akademik_Ders_Öğrenci { get; set; }
    }
}
