//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Yorum_Id { get; set; }
        public Nullable<int> Öğrenci_Id { get; set; }
        public Nullable<int> Danışman_Id { get; set; }
        public string Yorum1 { get; set; }
        public Nullable<System.DateTime> Yorum_Tarihi { get; set; }
    
        public virtual Danışman Danışman { get; set; }
        public virtual Öğrenci Öğrenci { get; set; }
    }
}
