//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yönetme_Yeteneği
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yönetme_Yeteneği()
        {
            this.Kanaat_Formu = new HashSet<Kanaat_Formu>();
        }
    
        public int Yönetme_Yeteneği_Id { get; set; }
        public Nullable<int> Problem_Çözüm { get; set; }
        public Nullable<int> Org_Koord_Yetenek { get; set; }
        public Nullable<int> İletişim_Yetenek { get; set; }
        public Nullable<double> Yönetme_Yet_Ort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanaat_Formu> Kanaat_Formu { get; set; }
    }
}
