//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeveritabanıdeneme.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Çalışma_Yeteneği
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Çalışma_Yeteneği()
        {
            this.Kanaat_Formu = new HashSet<Kanaat_Formu>();
        }
    
        public int Çalişma_Yeteneği_Id { get; set; }
        public Nullable<int> Mesleki_Uygulama_Yeteneği { get; set; }
        public Nullable<int> Bilimsellik { get; set; }
        public Nullable<int> Ekip_Çalışması_Uyum { get; set; }
        public Nullable<double> Çalışma_Yeteneği_Ort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanaat_Formu> Kanaat_Formu { get; set; }
    }
}
